Multi test suite execution via cobtest (#83)
* renamed cobtest

* added new tree traversal with cobtest which invokes cobtest

* added RETURN-CODE setting if the test has fails

* added eof newline chars and code cov comment

* added DUT-SET-RETURN-CODE section with test cases

diff --git a/cobtest b/cobtest
--- a/cobtest
+++ b/cobtest
@@ -1,38 +1,64 @@
-#!/bin/sh
+#!/bin/bash
 
-# Business program is identified by: src/main/cobol/sorlib/**.cbl
-business_pgm=src/main/cobol/sorlib/pgm-to-test.cbl
+num_test_files=0
+num_suite_fail=0
+num_suite_pass=0
 
-# For every business program
-# Test program is: src/test/cobol/testlib/<directory-to-source-code>/*.cbl
-test_pgm=src/test/cobol/testlib/pgm-to-test/test-pgm.cbl
+failed_suites=""
 
-printf "Stage 0 - Instrumenting Code Coverage\n"
-printf "===================================================\n"
+for source in `find src/main/cobol/sorlib/ -name "**.cbl" 2> /dev/null`; do
+    echo "Discovered source file: $source"
+    path=${source%.*}
 
-# If running without code-coverage-precompiler, skip this step and point harness.sh directly at the program under test
-mkdir coverage tmp
-tmp_coverage_pgm=coverage/pgm-to-test.cbl
-code-coverage-precompiler.sh $business_pgm $tmp_coverage_pgm &&
+    test_directory="${path/src\/main\/cobol\/sorlib/src\/test\/cobol\/testlib}"
+    
+    expression=$test_directory"/**.cbl"
+    test_files=`find $expression 2> /dev/null`
+    for test_program in $test_files; do
+        num_test_files=$(($num_test_files+1))
+        echo "    Found test program:" $test_program
+        echo ""
+        
+        if ! ./cobtestrun $source $test_program; then
+            #echo "TEST FAILS DETECTED IN" $test_program
+            failed_suites+="${test_program}\n"
+            num_suite_fail=$(($num_suite_fail+1))
+        else
+            num_suite_pass=$(($num_suite_pass+1))
+        fi
 
-printf "\nStage 1 - Running the harness\n"
-printf "===================================================\n"
-./harness.sh $tmp_coverage_pgm $test_pgm &&
+    done
 
-printf "\nStage 2 - Compile\n"
-printf "===================================================\n"
-cobc -x test-pgm-out.cbl -o testpgm -I "CUT" -I "tmp" &&
+    if [[ $test_files == "" ]]; then
+        echo "    No test programs found:"
+    fi
+    echo ""
+    echo ""
+done
 
-printf "\nStage 3 - Execute\n"
-printf "===================================================\n"
-./testpgm > Reports/dut-coverage-report.txt; cp CUT-RPTO "Reports/Unit Test Report.txt" &&
+printf "\n\n"
+echo "==================================================="
+if [[ $num_suite_fail = 0 ]]; then
+    echo "COBOL Unit Test Complete"
+else
+    echo "COBOL Unit Test Failed"
+fi
+echo "==================================================="
+echo ""
+echo "Detected " $num_test_files " test suites(s)"
+echo ""
+echo "==================================================="
+echo "Failed Suite(s): $num_suite_fail"
+echo "Passed Suite(s): $num_suite_pass"
+echo "==================================================="
 
-printf "\n"
 
-grep -E -B 1 -A 1 '^\[(FAIL|ERROR|SKIP|DEBUG)\]' CUT-RPTO
 
-printf "\n"
 
-cat CUT-RPTO | tail -7
-
-rm -r coverage tmp CUT-RPTO testpgm test-pgm-out.cbl
+if [[ num_suite_fail -gt 0 ]]; then
+    echo ""
+    echo "Failed Suites:"
+    printf $failed_suites
+    
+    exit 1
+fi
